import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import earth from '/public/earth.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.welcome}>
        <span style={{ color: 'grey' }}>Welcome to{'\n'}</span>
        <span style={{ color: 'hotpink' }}>Weather App!</span>
      </h1>
      
      <p className={styles.detail}>Choose a city from the list below to check the weather.</p>
      
      {/* <p>Hover</p> */}

      <div style={{position: 'relative'}}>
        {/* <div className={styles.activeButton}>
          
          <button className={styles.button}>Seoul</button>
          <p>Select</p>
          <button className={styles.button}>Seoul</button>
        </div> */}

        <div className={styles.cityButton}>
          <button className={styles.button}>Seoul</button>
          <button className={styles.button}>Tokyo</button>
          <button className={styles.button}>Paris</button>
          <button className={styles.button}>London</button>
        </div>
      </div>

      <Image src={earth} alt='지구' className={styles.earthImg}/>
      
    </div>
  )
}
